### ISSUE TITLE
Vaadin Projekt anlegen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri-vaadin#2]
Es soll ein "Hello-World"-Projekt angelegt werden, damit hiermit die Adapter umgesetzt werden können.

- [x] Das Projekt ist im KoliBri-Vaadin Repo abgelegt

**Comment by sdvg** [comment]
Das Beispiel ist jetzt bereits im `main`-Branch, weil es zuvor keinen Branch gab und mein gepushter Branch automatisch zum Standard-Branch wurde.
Mgl. Nacharbeiten aus dem Review würde ich in einem neuen PR erledigen.
